# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - main.css
    - //api.tiles.mapbox.com/mapbox.js/v2.1.4/mapbox.css

  javascripts:
    - //cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js
    - //api.tiles.mapbox.com/mapbox.js/v2.1.4/mapbox.js

  has_layout:     true
  layout:         layout
